### ISSUE TITLE
“./sbtwrapper ui/assembly“  Packaging error  “java.io.IOException: Cannot run program "npm" (in directory "ui\client"): CreateProcess error=2“

### ISSUE THREAD

**Issue by tianhuaxing** [TouK/nussknacker#10]
executive command ./sbtwrapper ui/assembly exception，This "npm" environment variable is already matched.  this is window!

java.io.IOException: Cannot run program "npm" (in directory "ui\client"): CreateProcess error=2, ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at $737037a525ee067296c3$.runNpm(build.sbt:11)
        at $737037a525ee067296c3$$anonfun$ui$1.apply$mcV$sp(build.sbt:532)
        at $737037a525ee067296c3$$anonfun$ui$1.apply(build.sbt:531)
        at $737037a525ee067296c3$$anonfun$ui$1.apply(build.sbt:531)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at $737037a525ee067296c3$.runNpm(build.sbt:11)
        at $737037a525ee067296c3$$anonfun$ui$1.apply$mcV$sp(build.sbt:532)
        at $737037a525ee067296c3$$anonfun$ui$1.apply(build.sbt:531)
        at $737037a525ee067296c3$$anonfun$ui$1.apply(build.sbt:531)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (ui/*:buildUi) java.io.IOException: Cannot run program "npm" (in directory "ui\client"): CreateProcess error=2, ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

How can I solve it?

**Comment by jwzhu** [comment]
You should run it under linux os with npm command supported.
