### ISSUE TITLE
Happen an error when to click button 'CREATE NEW PROCESS' in Running IDEA.

### ISSUE THREAD

**Issue by MicDP** [TouK/nussknacker#11]
14:41:41.131 [nussknacker-ui-akka.actor.default-dispatcher-44] INFO  p.t.n.e.m.RestartableFlinkGateway - Creating new gateway
14:41:41.138 [nussknacker-ui-akka.actor.default-dispatcher-44] WARN  p.t.n.ui.api.ProcessesResources - Failed to get status of demo: Config parameter 'Key: 'jobmanager.rpc.address' , default: null (deprecated keys: [])' is missing (hostname/address of JobManager to connect to).
org.apache.flink.util.ConfigurationException: Config parameter 'Key: 'jobmanager.rpc.address' , default: null (deprecated keys: [])' is missing (hostname/address of JobManager to connect to).
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.getJobManagerAddress(HighAvailabilityServicesUtils.java:129) ~[flink-runtime_2.11-1.4.2.jar:1.4.2]
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:77) ~[flink-runtime_2.11-1.4.2.jar:1.4.2]
	at org.apache.flink.client.program.ClusterClient.<init>(ClusterClient.java:144) ~[flink-clients_2.11-1.4.2.jar:1.4.2]
	at org.apache.flink.client.program.StandaloneClusterClient.<init>(StandaloneClusterClient.java:44) ~[flink-clients_2.11-1.4.2.jar:1.4.2]
	at pl.touk.nussknacker.engine.management.DefaultFlinkGateway.createClient(FlinkGateway.scala:47) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.DefaultFlinkGateway.<init>(FlinkGateway.scala:24) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.FlinkProcessManager$.pl$touk$nussknacker$engine$management$FlinkProcessManager$$prepareGateway(FlinkProcessManager.scala:42) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.FlinkProcessManager$$anonfun$apply$2.apply(FlinkProcessManager.scala:36) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.FlinkProcessManager$$anonfun$apply$2.apply(FlinkProcessManager.scala:36) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.RestartableFlinkGateway.retrieveGateway(FlinkGateway.scala:96) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.RestartableFlinkGateway.pl$touk$nussknacker$engine$management$RestartableFlinkGateway$$tryToInvokeJobManager(FlinkGateway.scala:72) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.RestartableFlinkGateway.invokeJobManager(FlinkGateway.scala:62) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.FlinkProcessManager.listJobs(FlinkProcessManager.scala:188) ~[classes/:na]
	at pl.touk.nussknacker.engine.management.FlinkProcessManager.findJobStatus(FlinkProcessManager.scala:129) ~[classes/:na]
	at pl.touk.nussknacker.ui.process.deployment.ManagementActor$$anonfun$receive$1$$anonfun$2.apply(ManagementActor.scala:64) ~[classes/:na]
	at pl.touk.nussknacker.ui.process.deployment.ManagementActor$$anonfun$receive$1$$anonfun$2.apply(ManagementActor.scala:63) ~[classes/:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36) [scala-library-2.11.12.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.4.20.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.4.20.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.4.20.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.4.20.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.12.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.4.20.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) [akka-actor_2.11-2.4.20.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415) [akka-actor_2.11-2.4.20.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.12.jar:na]

**Comment by lciolecki** [comment]
This is no bug. Before run nussknacker from IDEA you sould run: sbt assembly for create jar's dependencies.
