### ISSUE TITLE
Problems with buildServer.sh

### ISSUE THREAD

**Issue by RussoIvan** [TouK/nussknacker#19]
Hi, I have several errors when I try to compile "ui" via "buildServer.sh" or "build.sbt".

In order the problems i encounter are :

1)

```
[error] /home/io/Scaricati/nussknacker-master/engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaEspUtils.scala:53:56: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match expected type java.util.Map[String,String] => ?
[error]     config.kafkaProperties.map(_.asJava).foreach(props.putAll)
[error]                                                        ^
[error] one error found
```

2) I tried to update package.json to avoid this, but without any postive response.
```
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN schema-utils@0.4.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-loader@5.3.3 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@1.2.7 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@3.1.2 requires a peer of webpack@^4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-dnd@2.1.2 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@1.6.0 requires a peer of moment@^2.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@1.6.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datepicker@1.6.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-onclickoutside@6.7.1 requires a peer of react@^15.5.x || ^16.x but none is installed. You must install peer dependencies yourself.
npm WARN react-onclickoutside@6.7.1 requires a peer of react-dom@^15.5.x || ^16.x but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-pure-render-mixin@0.14.8 requires a peer of react@^0.14.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```

3)
```
> esp-ui-client@0.0.0 build /home/io/Scaricati/nussknacker-master/ui/client
> NODE_ENV=production webpack -p --progress && cp -R assets/icons/license dist

/bin/sh: 1: git: not found
child_process.js:677
    throw err;
    ^

Error: Command failed: git log -1 --format=%H
/bin/sh: 1: git: not found

    at checkExecSyncError (child_process.js:637:11)
    at Object.execSync (child_process.js:674:13)
    at Object.<anonymous> (/home/io/Scaricati/nussknacker-master/ui/client/webpack.config.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esp-ui-client@0.0.0 build: `NODE_ENV=production webpack -p --progress && cp -R assets/icons/license dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esp-ui-client@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-19T17_15_47_794Z-debug.log
[error] java.lang.RuntimeException: Client build failed
[error] 	at $bd43d95d8e743fc8ac8c$.runNpm(build.sbt:585)
[error] 	at $bd43d95d8e743fc8ac8c$.$anonfun$ui$2(build.sbt:603)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (ui/*:buildUi) Client build failed

```

This is the debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.8.0
3 info using node@v11.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle esp-ui-client@0.0.0~prebuild: esp-ui-client@0.0.0
6 info lifecycle esp-ui-client@0.0.0~build: esp-ui-client@0.0.0
7 verbose lifecycle esp-ui-client@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle esp-ui-client@0.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/io/Scaricati/nussknacker-master/ui/client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle esp-ui-client@0.0.0~build: CWD: /home/io/Scaricati/nussknacker-master/ui/client
10 silly lifecycle esp-ui-client@0.0.0~build: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=production webpack -p --progress && cp -R assets/icons/license dist' ]
11 silly lifecycle esp-ui-client@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle esp-ui-client@0.0.0~build: Failed to exec build script
13 verbose stack Error: esp-ui-client@0.0.0 build: `NODE_ENV=production webpack -p --progress && cp -R assets/icons/license dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid esp-ui-client@0.0.0
15 verbose cwd /home/io/Scaricati/nussknacker-master/ui/client
16 verbose Linux 4.15.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v11.10.0
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error esp-ui-client@0.0.0 build: `NODE_ENV=production webpack -p --progress && cp -R assets/icons/license dist`
22 error Exit status 1
23 error Failed at the esp-ui-client@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

What am I doing wrong?
Thanks in advance.

**Comment by mproch** [comment]
Hello,
what scala/java and npm/node versions are you using?
The first error seems like java/scala version problem - so far we support only java 8 and scala 2.11 (we should upgrade to scala 2.12 shortly) 
And the npm error says you don't have git installed - guess it's prequisite for git-revision-webpack-plugin

**Comment by witekw** [comment]
Closed due to innactivity.
