### ISSUE TITLE
The Demo Processe can't work

### ISSUE THREAD

**Issue by echooymxq** [TouK/nussknacker#435]
**Describe the bug**
I clone the latest master branch, and run the demo docker, import the DetectLargeTransactions.json and deploy it . After the previous step is completed, i run the sendTestTransactions.sh to send data to kafka.
But at Flink Dashboard , the job exception show below.
`pl.touk.nussknacker.engine.api.CirceUtil$DecodingError: Failed to decode - , error: Attempt to decode value on failed cursor: DownField(eventDate)
	at pl.touk.nussknacker.engine.api.CirceUtil$.unsafe(CirceUtil.scala:26)
	at pl.touk.nussknacker.engine.api.CirceUtil$.decodeJsonUnsafe(CirceUtil.scala:23)
	at pl.touk.nussknacker.engine.example.ExampleProcessConfigCreator.$anonfun$createTransactionSource$1(ExampleProcessConfigCreator.scala:67)
	at pl.touk.nussknacker.engine.example.ExampleProcessConfigCreator.$anonfun$kafkaSource$1(ExampleProcessConfigCreator.scala:78)
	at pl.touk.nussknacker.engine.flink.util.source.EspDeserializationSchema.deserialize(EspDeserializationSchema.scala:10)
	at org.apache.flink.streaming.util.serialization.KeyedDeserializationSchemaWrapper.deserialize(KeyedDeserializationSchemaWrapper.java:44)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka09Fetcher.runFetchLoop(Kafka09Fetcher.java:142)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:665)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:94)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:58)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:99)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
	at java.lang.Thread.run(Thread.java:748)
Caused by: DecodingFailure(Attempt to decode value on failed cursor, List(DownField(eventDate)))`
**I want to konw what happened, First use it**
**To Reproduce**
1. Having Flink and Nussknacker ran e.g. in docker
2. Open browser and go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Nussknacker version
 - Flink version
 - Java version
 - Method of ran of components [e.g. in docker, standalone]
 - Browser type and version [e.g. chrome 73]

**Additional context**

**Comment by arkadius** [comment]
Hi @echooymxq , thank you for a bug report. We will take a look at this.

**Comment by arkadius** [comment]
Strange ... I've just ran it the same way and haven't got such a behaviour. Can you send us information about you environment (mainly OS). From posted logs I guess that there is some problem with formatting sample json (missing `eventDate` field). Can you check if there are correct data on kafka? You can do it by invoking: `docker-compose exec kafka "/opt/kafka_2.12-2.2.0/bin/kafka-console-consumer.sh" --topic transactions --bootstrap-server localhost:9092 --from-beginning`

**Comment by echooymxq** [comment]
Sorry,It my mistake, The workspace at staging  branch previously. when i switch to the master branch, it can work. Thank you very much. @arkadius

**Comment by arkadius** [comment]
Still strange because it works for me also on staging branch. Gives us a shoot if you find out how to reproduce it.
Cheers and happy hacking of Nussknacker! :smile:
