### ISSUE TITLE
Happen an error when running 'buildServer.sh'

### ISSUE THREAD

**Issue by MicDP** [TouK/nussknacker#8]
[info] Set current project to nussknacker-master (in build file:/data/gits/nussknacker-master/)
Using path: /data/gits/nussknacker-master/ui/client
java.io.IOException: Cannot run program "npm" (in directory "ui/client"): error=2, 没有那个文件或目录
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at $c9bf2fb7fddbcc6c0d5b$.runNpm(build.sbt:11)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply$mcV$sp(build.sbt:532)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply(build.sbt:531)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply(build.sbt:531)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, 没有那个文件或目录
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at $c9bf2fb7fddbcc6c0d5b$.runNpm(build.sbt:11)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply$mcV$sp(build.sbt:532)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply(build.sbt:531)
        at $c9bf2fb7fddbcc6c0d5b$$anonfun$ui$1.apply(build.sbt:531)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (ui/*:buildUi) java.io.IOException: Cannot run program "npm" (in directory "ui/client"): error=2, 没有那个文件或目录
[error] Total time: 0 s, completed May 7, 2018 5:01:47 PM

**Comment by fijolekProjects** [comment]
Hi, you have to install `npm` first to be able to build ui - https://www.npmjs.com/
